### ISSUE TITLE
Use `poll/max_votes_amount` as maximum of yes votes for all yes-based poll methods

### ISSUE THREAD

**Issue by Shanksum** [OpenSlides/openslides-vote-service#202]
Elections in OpenSlides have the mandatory field to set a number of open posts. This should translate to the amount of allowed "Yes" votes on the ballot and thus invalidate the ballot if the user votes "Yes" on more people than the number of open posts.

In our experiments, we were not able to identify what the value for open posts even influences in how OpenSlides handles a vote. 

We think it should be at least an option to set the behavior for vote counting to invalidate votes in these cases, similar to how `maxVotesPerOption` is designed in the vote service.

**Comment by emanuelschuetze** [comment]
You should think about your right elction method:
Limitation of votes is useful only for election method YES-per-candidate. 
Usually, if you use YES-NO-ABSTAIN you have to vote for each candidate - without limitation.

If you have more candidates > open post then you should configure a YES-per-candidate election (with max amound of votes). If you have candidates <= open posts then you should configure YES-NO-ABSTAIN without limitation.

I don't like the suggestion to use open_posts for max_votes_amount for all new assignment polls because this does not support runoff votes (e.g. 2nd or 3rd ballots). Then the max_votes_amount changes for each ballot. The open_posts will be unchanged for the whole election.
